server:
    servlet:
        context-path: /library
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: admin
        url: jdbc:h2:mem:demodb
        username: admin
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
    h2:
        console:
            enabled: true
